# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_PyDFYCPcIwMeGpKGThmAx8LU
# stripe_publishable_key: pk_test_3I2BMssod47EfFSJ8l4nm9SG
#

development:
  stripe_secret_key: sk_test_PyDFYCPcIwMeGpKGThmAx8LU
  stripe_publishable_key: pk_test_3I2BMssod47EfFSJ8l4nm9SG
  secret_key_base: 75b34d0e0e38be67cc038e5b2325b6c92206966fa85d7238aae1096750a11b2534a028a2e80d8eb751b3fb4d085b29ea4c8ed92623c517f1e6ad877419d5f04f

test:
  stripe_secret_key: sk_test_PyDFYCPcIwMeGpKGThmAx8LU
  stripe_publishable_key: pk_test_3I2BMssod47EfFSJ8l4nm9SG
  secret_key_base: f17a27c6b1b3bef6dd50f3b2430b38023d6717b3392abcb5c36be9b4d467e89e536b91b67ef6dd16cf157c9d452a293b31898ec6a3957189498190e12a61214f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  stripe_secret_key: sk_test_PyDFYCPcIwMeGpKGThmAx8LU
  stripe_publishable_key: pk_test_3I2BMssod47EfFSJ8l4nm9SG
